//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeltaMovieDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public Movie()
        {
            this.ActorMovies = new HashSet<ActorMovie>();
        }
    
        public int MovieId { get; set; }
        public string Name { get; set; }
        public int YearOfRelease { get; set; }
        public string Plot { get; set; }
        public byte[] Poster { get; set; }
        public int ProducerId { get; set; }
    
        public virtual ICollection<ActorMovie> ActorMovies { get; set; }
        public virtual Producer Producer { get; set; }
    }
}
